IMAGE_SIZE: [224, 224, 3]
WEIGHTS: imagenet
INCLUDE_TOP: false
POOLING: avg
CNN_DIM: 2048
EMBEDDING_DIM: 256
LSTM_UNITS: 512
DROPOUT: 0.5
LEARNING_RATE: 0.001
CLIPNORM: 1.0
SPLIT_SIZE: 0.2
RANDOM_STATE: 42
BATCH_SIZE: 32
VOCAB_SIZE: 8588
MAX_LENGTH: 35
